# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:00:04+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Header, Query

from models import ForecastGetResponse, ProtectionResult, UvIndexResult

app = MCPProxy(
    description='The missing minimalistic JSON real-time UV Index API for awesome Developers, Innovators and Smart Home Enthusiasts',
    title='OpenUV - Global Real-Time UV Index Forecast API',
    version='v1',
    servers=[
        {
            'url': 'https://api.openuv.io/api/{version}',
            'variables': {'version': {'default': 'v1'}},
        }
    ],
)


@app.get(
    '/forecast',
    description=""" Get hourly UV Index Forecast by location and date. Optional altitude, ozone level and datetime could be provided. """,
    tags=['uv_index_monitoring', 'air_quality_assessment'],
)
def get_forecast(
    lat: float,
    lng: float = ...,
    alt: Optional[float] = None,
    ozone: Optional[float] = None,
    dt: Optional[datetime] = None,
    x_access_token: str = Header(..., alias='x-access-token'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/protection',
    description=""" Get daily protection time by location, UV Index from and UV Index to with 10 minutes accuracy. Optional altitide and ozone level could be provided. """,
    tags=['uv_index_monitoring', 'air_quality_assessment'],
)
def get_protection(
    lat: float,
    lng: float = ...,
    from_: float = Query(..., alias='from'),
    to: float = ...,
    alt: Optional[float] = None,
    ozone: Optional[float] = None,
    x_access_token: str = Header(..., alias='x-access-token'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/uv',
    description=""" Get real-time UV Index by location. Optional altitude, ozone level and datetime could be provided. """,
    tags=['weather_forecasting', 'uv_index_monitoring', 'air_quality_assessment'],
)
def get_uv(
    lat: float,
    lng: float = ...,
    alt: Optional[float] = None,
    ozone: Optional[float] = None,
    dt: Optional[datetime] = None,
    x_access_token: str = Header(..., alias='x-access-token'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
