# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:00:04+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field, RootModel


class Error(BaseModel):
    error: str


class Forecast(BaseModel):
    uv: float
    uv_time: str


class ForecastResult(RootModel[List[Forecast]]):
    root: List[Forecast] = Field(..., title='result')


class ProtectionResult(BaseModel):
    ozone: float
    ozone_time: str
    uv: float
    uv_max: float
    uv_max_time: str
    uv_time: str


class UvIndexResult(BaseModel):
    from_time: str
    from_uv: float
    to_time: str
    to_uv: float


class ForecastGetResponse(RootModel[List[ForecastResult]]):
    root: List[ForecastResult]
